# Generated by Django 4.0.2 on 2022-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_id_alter_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
