# Generated by Django 4.0.2 on 2022-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_videofile_lesson_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videofile',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
