# Generated by Django 4.0.2 on 2023-01-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('membership', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTransaction',
            new_name='PaymentTransactionn',
        ),
    ]
