# Generated by Django 4.0.2 on 2023-01-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('membership', '0009_rename_paymenttransaction_paymenttransactionn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTransactionn',
            new_name='PaymentTransaction',
        ),
    ]
