# Generated by Django 4.0.2 on 2022-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videofile',
        ),
        migrations.AddField(
            model_name='lesson',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
