# Generated by Django 4.0.2 on 2022-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lesson_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
